name: shell commands

on: [push]
    
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo string
        run: echo "This is the first step of my first job."
      - name: multi string
        run: |
          node -v
          npm -v
          
